### ISSUE TITLE
Add 'pulumi stack init' and 'stack rm' commands

### ISSUE THREAD

**Issue by chrsmith** [pulumi/circleci#10]
Add support in the Pulumi orbs for the `pulumi stack init` and `pulumi stack rm` commands. This would allow for fully automating the lifecycle of a Pulumi program, e.g. as part of a "review app" or integration test scenario.

See documentation for the commands at:
https://www.pulumi.com/docs/reference/cli/pulumi_stack/

**Comment by kenfdev** [comment]
First time contribution but let me take this 😉
