### ISSUE TITLE
[Feature Request] Add support to `ci.json`

### ISSUE THREAD

**Issue by iagomelanias** [pulumi/circleci#2]
Hi! 👋
Currently, the [Pulumi Actions](https://github.com/pulumi/actions) has a different behavior.

1. It automatically determines the stack name by using the `ci.json` file.
2. If it's a pull request, it uses the target branch name.

It would be great to have these same features here, so we don't need to write multiple jobs for every stack. 😅

**Comment by chrsmith** [comment]
Sounds like a good thing to add, obviously having a single way to map Pulumi stacks and CI/CD workflows is the way to go. 👍
